"""Change birthday type to date

Revision ID: 27c65b64848d
Revises: cdf316040ebd
Create Date: 2025-12-03 15:46:13.652340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27c65b64848d"
down_revision: Union[str, Sequence[str], None] = "cdf316040ebd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "birthday",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Date(),
        existing_nullable=False,
        postgresql_using="birthday::date",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts",
        "birthday",
        existing_type=sa.Date(),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
