"""role as enum

Revision ID: 9fb13c96724f
Revises: 27c65b64848d
Create Date: 2025-12-17 11:21:58.909719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb13c96724f'
down_revision: Union[str, Sequence[str], None] = '27c65b64848d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1. Оголошуємо наш Enum (такий самий, як у Python коді)
    # Важливо: name='userrole' має збігатися з тим, що в базі
    user_role_enum = sa.Enum('admin', 'user', name='userrole')
    
    # 2. Створюємо цей тип у базі даних
    user_role_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=user_role_enum,
               existing_nullable=False,
               postgresql_using="role::userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('admin', 'user', name='userrole')

    op.alter_column('users', 'role',
               existing_type=user_role_enum,
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
